name: NodeTest

on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
    matrix:
     node-version: [8.x, 10.x, 12.x]
     os: [macos-latest, windows-latest, ubuntu-18.04]

     steps:
     -name: Checkout code
     uses: actions/checkout@v1
     -name: Use Node.Js ${{matrix.node-version}}
     uses: actions/setup-node@v1
     with:
      node-version: ${{matrix.node-version}}
    -name: npm install, build and test
      run: |
        npm cli
        npm run build --if-present
        npm test
      env:
      CI: true
    -uses: actions/upload-artifact@master
    with:
      name: webpack artifacts
      path: /coverage/mochawesome-report/
